//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargos
    {
        public int CargoId { get; set; }
        public Nullable<int> Tipocargo { get; set; }
        public Nullable<int> Grupo { get; set; }
        public string descripción { get; set; }
        public Nullable<decimal> coste { get; set; }
        public Nullable<decimal> precio1 { get; set; }
        public Nullable<decimal> precio2 { get; set; }
        public Nullable<decimal> precio3 { get; set; }
        public Nullable<decimal> precio4 { get; set; }
        public Nullable<decimal> precio5 { get; set; }
        public Nullable<bool> inventario { get; set; }
        public Nullable<bool> Kit { get; set; }
        public Nullable<bool> agrupable { get; set; }
        public string presentacion { get; set; }
        public string indicaciones { get; set; }
        public Nullable<bool> activo { get; set; }
        public string via { get; set; }
    }
}
