//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINICA
    {
        public int IDCLINICA { get; set; }
        public string CLINICA1 { get; set; }
        public string RIF { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion2 { get; set; }
        public string Direccion3 { get; set; }
        public string Direccion4 { get; set; }
        public string Ciudad { get; set; }
        public string Telefonos { get; set; }
        public string responsable { get; set; }
        public string DirectorioImagenes { get; set; }
        public string DirectorioExportados { get; set; }
        public string Correo { get; set; }
        public string ArchivoLogo { get; set; }
        public string numerodeLicencia { get; set; }
        public Nullable<System.DateTime> FechadeInstalación { get; set; }
    }
}
