//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correlativos
    {
        public int Id { get; set; }
        public Nullable<long> FACTURA { get; set; }
        public Nullable<long> PRESUPUESTO { get; set; }
        public Nullable<long> LABORATORIO { get; set; }
        public Nullable<long> INFORMEMEDICO { get; set; }
        public Nullable<long> HOSPITALIZACION { get; set; }
        public Nullable<long> OTRO1 { get; set; }
        public Nullable<long> OTRO2 { get; set; }
        public string EQUIPO { get; set; }
    }
}
