//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AGILMEDEntities : DbContext
    {
        public AGILMEDEntities()
            : base("name=AGILMEDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ciudades> Ciudades { get; set; }
        public DbSet<Estados> Estados { get; set; }
        public DbSet<PACIENTES> PACIENTES { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Ocupaciones> Ocupaciones { get; set; }
        public DbSet<Empresas> Empresas { get; set; }
        public DbSet<Dependientes> Dependientes { get; set; }
        public DbSet<Cargos> Cargos { get; set; }
        public DbSet<CargosClases> CargosClases { get; set; }
        public DbSet<DetalleFactura> DetalleFactura { get; set; }
        public DbSet<Documentos> Documentos { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<TipodeCargos> TipodeCargos { get; set; }
        public DbSet<Correlativos> Correlativos { get; set; }
        public DbSet<LOCAL> LOCAL { get; set; }
        public DbSet<CLINICA> CLINICA { get; set; }
        public DbSet<Subproductos> Subproductos { get; set; }
        public DbSet<Ingresos> Ingresos { get; set; }
        public DbSet<Eventos> Eventos { get; set; }
        public DbSet<medicos> medicos { get; set; }
        public DbSet<Especialidades> Especialidades { get; set; }
        public DbSet<diagnosticos> diagnosticos { get; set; }
        public DbSet<medicinas> medicinas { get; set; }
        public DbSet<recipes> recipes { get; set; }
        public DbSet<sintomas> sintomas { get; set; }
    }
}
