//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependientes
    {
        public long Dependienteid { get; set; }
        public string Nombre { get; set; }
        public int Parentesco { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Identificacion { get; set; }
        public Nullable<long> PacienteId { get; set; }
    }
}
