//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public string Factura { get; set; }
        public long idcargo { get; set; }
        public int cantidad { get; set; }
        public decimal preciounitario { get; set; }
        public Nullable<decimal> iva { get; set; }
        public decimal monto { get; set; }
        public int tipocargo { get; set; }
        public int clase { get; set; }
        public bool totaliza { get; set; }
        public string observaciones { get; set; }
        public long idfactura { get; set; }
    }
}
