//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public Nullable<long> idPaciente { get; set; }
        public string TipoDocumento { get; set; }
        public string observaciones { get; set; }
        public long idDocumento { get; set; }
        public string Archivo { get; set; }
        public byte[] Fecha { get; set; }
    }
}
