//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public int Id { get; set; }
        public string Empresa { get; set; }
        public string RIF { get; set; }
        public string Direccion { get; set; }
        public string Contacto { get; set; }
        public string Telefonos { get; set; }
        public string Correo { get; set; }
        public byte[] created { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Aseguradora { get; set; }
        public Nullable<int> creditodias { get; set; }
        public Nullable<decimal> limite { get; set; }
    }
}
