//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public Nullable<long> admisionid { get; set; }
        public long idevento { get; set; }
        public Nullable<int> tipoevento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public byte[] auditoria { get; set; }
        public Nullable<int> usuarioid { get; set; }
    }
}
