//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public long IdFactura { get; set; }
        public string Factura1 { get; set; }
        public string Control { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<long> Para { get; set; }
        public Nullable<long> Paciente { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<int> FormadePago { get; set; }
        public string rif { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> neto { get; set; }
        public Nullable<decimal> Descuentos { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> anio { get; set; }
        public string codigodecuenta { get; set; }
    }
}
