//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public long admisionid { get; set; }
        public System.DateTime fechaingreso { get; set; }
        public Nullable<System.DateTime> fechasalida { get; set; }
        public Nullable<int> procesada { get; set; }
        public int motivo { get; set; }
        public string observaciones { get; set; }
        public int tipodeingreso { get; set; }
        public string ticket { get; set; }
        public string clave { get; set; }
        public byte[] created { get; set; }
        public long trabajadorid { get; set; }
        public string cedulatrabajador { get; set; }
        public long dependienteid { get; set; }
        public string nombrepaciente { get; set; }
        public string ceduladebeneficiario { get; set; }
        public bool esbeneficiario { get; set; }
        public string cedulapaciente { get; set; }
        public int usuarioid { get; set; }
        public Nullable<long> refieremedico { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> aseguradoraid { get; set; }
    }
}
