//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCAL
    {
        public int Id { get; set; }
        public string EQUIPO { get; set; }
        public string CAMARAWEB { get; set; }
        public string SCANNER { get; set; }
        public string IMPRESORA { get; set; }
        public string IMPRESORA2 { get; set; }
    }
}
