//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicos
    {
        public int doctorid { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string telefono2 { get; set; }
        public Nullable<bool> activo { get; set; }
        public string horariodeconsulta { get; set; }
        public Nullable<int> especialidad { get; set; }
        public string ncm { get; set; }
        public Nullable<bool> especialista { get; set; }
    }
}
