//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipes
    {
        public long ingresoid { get; set; }
        public long recipeid { get; set; }
        public long pacienteid { get; set; }
        public int doctorid { get; set; }
        public int medicamentoid { get; set; }
        public string indicaciones { get; set; }
        public string observaciones { get; set; }
        public byte[] fecha { get; set; }
    }
}
