//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuarioId { get; set; }
        public string Usuario { get; set; }
        public bool activo { get; set; }
        public int TipodeAcceso { get; set; }
        public string Modulos { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public byte[] created { get; set; }
        public Nullable<decimal> Rol { get; set; }
        public string Correo { get; set; }
        public string telefono { get; set; }
        public string Nombres { get; set; }
        public string password { get; set; }
    }
}
